### ISSUE TITLE
Firefox support?

### ISSUE THREAD

**Issue by omkarnathsingh** [radibit/jira-dark-theme#1]
Can we apply for firefox? How?

**Comment by radibit** [comment]
Hey, since this project is most likely outdated and it was using a tiny CSS snippet to achieve the effect 2 years ago, I'd recommend now the following combination:

- https://addons.mozilla.org/en-US/firefox/addon/styl-us/
- https://userstyles.org/styles/111929/jira-dark-improved

🙂

**Comment by omkarnathsingh** [comment]
Thanks @radibit  :) Working good enough
